vim.api.nvim_set_hl(0, 'SignColumn', { bg='NONE' })
vim.api.nvim_set_hl(0, 'pmenu', { fg='white', bg='#4d4d4d' })
vim.api.nvim_set_hl(0, 'pmenusel', { fg='black', bg='#C7B446' })
vim.api.nvim_set_hl(0, 'WinSeparator', { bg='NONE' })
vim.api.nvim_set_hl(0, 'StatusLine', { bg='yellow', fg='black' })
